# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    # Agrega una lista de dependencias que quieres excluir de las actualizaciones automáticas.
    # Esto es útil si tienes dependencias que son propensas a romper con actualizaciones automáticas.
    # Aquí tienes un ejemplo, pero puedes agregar más dependencias según tus necesidades:
    filters:
      - update-ignore:
          - dependency-name: "nombre-de-la-dependencia-a-excluir"
          - dependency-name: "otra-dependencia-a-excluir"

    "maven":
      "pom":
        # Si tu archivo pom.xml está en la raíz del proyecto, no necesitas especificar nada aquí.
        # Si está en una subcarpeta, por ejemplo, "backend/pom.xml", asegúrate de especificar la ruta completa.
        - "pom.xml"

