# Qodana Code Quality Scan
#
# This workflow runs the Qodana scan on pull requests, pushes to the main branch, and releases branches.
# Qodana is a code quality and static analysis tool by JetBrains.
#
# Qodana GitHub Action: https://github.com/JetBrains/qodana-action

name: Qodana Code Quality Scan

# Define los eventos que activarán este flujo de trabajo.
on:
  # workflow_dispatch te permite ejecutar manualmente el flujo de trabajo desde la interfaz de GitHub.
  workflow_dispatch:
  # Se ejecutará cuando haya una solicitud de extracción (pull request) creada o actualizada.
  pull_request:
  # Se ejecutará cuando haya un push al repositorio.
  push:

jobs:
  # Define el trabajo llamado "qodana-scan".
  qodana-scan:
    # Define el sistema operativo en el que se ejecutará el trabajo.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # Paso para clonar el código fuente del repositorio en la máquina de ejecución.
        uses: actions/checkout@v3
        # El argumento "fetch-depth: 0" permite clonar todo el historial del repositorio en lugar de solo el último commit.
        with:
          fetch-depth: 0

      - name: Qodana Scan
        # Utiliza la acción "JetBrains/qodana-action@v2022.3.3" para realizar el análisis de calidad de código con Qodana.
        uses: JetBrains/qodana-action@v2022.3.3
        env:
          # Define una variable de entorno llamada "QODANA_TOKEN" y se le asigna el valor del secreto "QODANA_TOKEN" almacenado en los secretos de GitHub.
          # Este token es necesario para autenticar la acción de Qodana con el servicio de JetBrains.
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

