name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # Clona el código fuente del repositorio en la máquina de ejecución.

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
        # Configura el entorno de ejecución con JDK 17 utilizando Temurin (una distribución de OpenJDK).

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
        # Almacena en caché las dependencias de Maven para mejorar el tiempo de ejecución.

      - name: Build with Maven
        run: mvn clean test
        # Ejecuta las pruebas unitarias del proyecto.

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        # Construye el proyecto y empaqueta la aplicación en un archivo JAR u otro formato.

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
        # Actualiza el gráfico de dependencias del proyecto.


