name: Docker Build and Push

on:
  push:
    # Este flujo de trabajo se activará cuando se hagan cambios en la rama "main".
    branches:
      - main

jobs:
  docker_build_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # Clonar el código fuente del repositorio en la máquina de ejecución.
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        # Configurar Docker Buildx para admitir la compilación y el push de imágenes Docker.
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        # Iniciar sesión en Docker Hub utilizando las credenciales almacenadas como secretos en el repositorio.
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        # Utilizar la acción "docker/build-push-action@v2" para compilar y empujar la imagen Docker a Docker Hub.
        uses: docker/build-push-action@v2
        with:
          context: . # Especificar el contexto de la compilación. En este caso, se toma el directorio raíz del repositorio como contexto.
          push: true # Indicar que queremos empujar la imagen al repositorio de Docker Hub.
          tags: alesanfel/TODOlist-API2:latest # Especificar las etiquetas de la imagen Docker que se va a construir y empujar.




